data:
  atadd_t1_train_audio: /root/autodl-fs/track1/train
  atadd_t1_train_label: /root/autodl-fs/track1/label/train.csv
  atadd_t1_dev_audio: /root/autodl-fs/track1/dev
  atadd_t1_dev_label: /root/autodl-fs/track1/label/dev.csv
  atadd_t1_eval_audio: /root/autodl-fs/track1/eval
ssl:
  xlsr: /root/autodl-fs/models/wav2vec2-xls-r-300m
  xlsr_selected_layers: [24]
  xlsr_layer_fusion: last

filter_types: speech
train_task: atadd-track1
out_fold: /root/autodl-fs/ckpt_t1/cqcc_ssl/cross_attn_assproj0_aug0.2_rawboost8_xlsr24_last

model: ft-cqccxlsraasist
save_best_by: loss
assist_project_choice: 0
cqcc_backend: torch
cqcc_torch_n_fft: 2048

aug:
  aug_speech: 0.2
  speech_aug_method: rawboost
  speech_rawboost_algo: 5

num_epochs:  100
batch_size:  48
lr:          0.000001
lr_decay:    0.5
interval:    2
num_workers: 4

eval_steps:        500
full_eval_steps:   3000
eval_warmup_steps: 3000
patience:          10
